/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: libi2pd.i

package i2pd

import "syscall"
import "unsafe"
import "sync"


type _ syscall.Sockaddr




type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func SwigCgocall()
func SwigCgocallDone()
func SwigCgocallBack()
func SwigCgocallBackDone()

//extern go.i2pd__wrap_Swig_free_i2pd_3cde21bb36a9caa1
func _swig_wrap_Swig_free(base uintptr)

func Swig_free(arg1 uintptr) {
	defer SwigCgocallDone()
	SwigCgocall()
	_swig_wrap_Swig_free(arg1)
}

//extern go.i2pd__wrap_Swig_malloc_i2pd_3cde21bb36a9caa1
func _swig_wrap_Swig_malloc(base int) (_ uintptr)

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_Swig_malloc(arg1)
}

//extern go.i2pd__wrap_i2p_set_i2pd_3cde21bb36a9caa1
func _swig_wrap_i2p_set(base uintptr)

func SetI2p(arg1 Namespace) {
	defer SwigCgocallDone()
	SwigCgocall()
	_swig_wrap_i2p_set(arg1.Swigcptr())
}

//extern go.i2pd__wrap_i2p_get_i2pd_3cde21bb36a9caa1
func _swig_wrap_i2p_get() (base SwigcptrNamespace)

func GetI2p() (_swig_ret Namespace) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_i2p_get()
}

const CODENAME string = "Purple"
const I2PD_VERSION_MAJOR int = 2
const I2PD_VERSION_MINOR int = 29
const I2PD_VERSION_MICRO int = 0
const I2PD_VERSION_PATCH int = 0
const I2PD_VERSION string = "2.29.0"
const VERSION string = "2.29.0"
const I2PD_NET_ID int = 2
const I2P_VERSION_MAJOR int = 0
const I2P_VERSION_MINOR int = 9
const I2P_VERSION_MICRO int = 43
const I2P_VERSION_PATCH int = 0
const I2P_VERSION string = "0.9.43"
const LEGACY_OPENSSL int = 1
//extern go.i2pd__wrap_DSA_set0_pqg_i2pd_3cde21bb36a9caa1
func _swig_wrap_DSA_set0_pqg(base uintptr, _ uintptr, _ uintptr, _ uintptr) (_ int)

func DSA_set0_pqg(arg1 DSA, arg2 BIGNUM, arg3 BIGNUM, arg4 BIGNUM) (_swig_ret int) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_DSA_set0_pqg(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr(), arg4.Swigcptr())
}

//extern go.i2pd__wrap_DSA_set0_key_i2pd_3cde21bb36a9caa1
func _swig_wrap_DSA_set0_key(base uintptr, _ uintptr, _ uintptr) (_ int)

func DSA_set0_key(arg1 DSA, arg2 BIGNUM, arg3 BIGNUM) (_swig_ret int) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_DSA_set0_key(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

//extern go.i2pd__wrap_DSA_get0_key_i2pd_3cde21bb36a9caa1
func _swig_wrap_DSA_get0_key(base uintptr, _ uintptr, _ uintptr)

func DSA_get0_key(arg1 DSA, arg2 BIGNUM, arg3 BIGNUM) {
	defer SwigCgocallDone()
	SwigCgocall()
	_swig_wrap_DSA_get0_key(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

//extern go.i2pd__wrap_DSA_SIG_set0_i2pd_3cde21bb36a9caa1
func _swig_wrap_DSA_SIG_set0(base uintptr, _ uintptr, _ uintptr) (_ int)

func DSA_SIG_set0(arg1 DSA_SIG, arg2 BIGNUM, arg3 BIGNUM) (_swig_ret int) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_DSA_SIG_set0(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

//extern go.i2pd__wrap_DSA_SIG_get0_i2pd_3cde21bb36a9caa1
func _swig_wrap_DSA_SIG_get0(base uintptr, _ uintptr, _ uintptr)

func DSA_SIG_get0(arg1 DSA_SIG, arg2 BIGNUM, arg3 BIGNUM) {
	defer SwigCgocallDone()
	SwigCgocall()
	_swig_wrap_DSA_SIG_get0(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

//extern go.i2pd__wrap_ECDSA_SIG_set0_i2pd_3cde21bb36a9caa1
func _swig_wrap_ECDSA_SIG_set0(base uintptr, _ uintptr, _ uintptr) (_ int)

func ECDSA_SIG_set0(arg1 ECDSA_SIG, arg2 BIGNUM, arg3 BIGNUM) (_swig_ret int) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_ECDSA_SIG_set0(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

//extern go.i2pd__wrap_ECDSA_SIG_get0_i2pd_3cde21bb36a9caa1
func _swig_wrap_ECDSA_SIG_get0(base uintptr, _ uintptr, _ uintptr)

func ECDSA_SIG_get0(arg1 ECDSA_SIG, arg2 BIGNUM, arg3 BIGNUM) {
	defer SwigCgocallDone()
	SwigCgocall()
	_swig_wrap_ECDSA_SIG_get0(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

//extern go.i2pd__wrap_RSA_set0_key_i2pd_3cde21bb36a9caa1
func _swig_wrap_RSA_set0_key(base uintptr, _ uintptr, _ uintptr, _ uintptr) (_ int)

func RSA_set0_key(arg1 RSA, arg2 BIGNUM, arg3 BIGNUM, arg4 BIGNUM) (_swig_ret int) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_RSA_set0_key(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr(), arg4.Swigcptr())
}

//extern go.i2pd__wrap_RSA_get0_key_i2pd_3cde21bb36a9caa1
func _swig_wrap_RSA_get0_key(base uintptr, _ uintptr, _ uintptr, _ uintptr)

func RSA_get0_key(arg1 RSA, arg2 BIGNUM, arg3 BIGNUM, arg4 BIGNUM) {
	defer SwigCgocallDone()
	SwigCgocall()
	_swig_wrap_RSA_get0_key(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr(), arg4.Swigcptr())
}

//extern go.i2pd__wrap_DH_set0_pqg_i2pd_3cde21bb36a9caa1
func _swig_wrap_DH_set0_pqg(base uintptr, _ uintptr, _ uintptr, _ uintptr) (_ int)

func DH_set0_pqg(arg1 DH, arg2 BIGNUM, arg3 BIGNUM, arg4 BIGNUM) (_swig_ret int) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_DH_set0_pqg(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr(), arg4.Swigcptr())
}

//extern go.i2pd__wrap_DH_set0_key_i2pd_3cde21bb36a9caa1
func _swig_wrap_DH_set0_key(base uintptr, _ uintptr, _ uintptr) (_ int)

func DH_set0_key(arg1 DH, arg2 BIGNUM, arg3 BIGNUM) (_swig_ret int) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_DH_set0_key(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

//extern go.i2pd__wrap_DH_get0_key_i2pd_3cde21bb36a9caa1
func _swig_wrap_DH_get0_key(base uintptr, _ uintptr, _ uintptr)

func DH_get0_key(arg1 DH, arg2 BIGNUM, arg3 BIGNUM) {
	defer SwigCgocallDone()
	SwigCgocall()
	_swig_wrap_DH_get0_key(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

//extern go.i2pd__wrap_EVP_PKEY_get0_RSA_i2pd_3cde21bb36a9caa1
func _swig_wrap_EVP_PKEY_get0_RSA(base uintptr) (_ SwigcptrRSA)

func EVP_PKEY_get0_RSA(arg1 EVP_PKEY) (_swig_ret RSA) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_EVP_PKEY_get0_RSA(arg1.Swigcptr())
}

//extern go.i2pd__wrap_EVP_MD_CTX_new_i2pd_3cde21bb36a9caa1
func _swig_wrap_EVP_MD_CTX_new() (base SwigcptrEVP_MD_CTX)

func EVP_MD_CTX_new() (_swig_ret EVP_MD_CTX) {
	defer SwigCgocallDone()
	SwigCgocall()
	return _swig_wrap_EVP_MD_CTX_new()
}

//extern go.i2pd__wrap_EVP_MD_CTX_free_i2pd_3cde21bb36a9caa1
func _swig_wrap_EVP_MD_CTX_free(base uintptr)

func EVP_MD_CTX_free(arg1 EVP_MD_CTX) {
	defer SwigCgocallDone()
	SwigCgocall()
	_swig_wrap_EVP_MD_CTX_free(arg1.Swigcptr())
}

//extern go.i2pd__wrap_QueueIntEvent_i2pd_3cde21bb36a9caa1
func _swig_wrap_QueueIntEvent(base uintptr, _ uintptr, _ uintptr)

func QueueIntEvent(arg1 Std_string, arg2 Std_string, arg3 Uint64_t) {
	defer SwigCgocallDone()
	SwigCgocall()
	_swig_wrap_QueueIntEvent(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr())
}

//extern go.i2pd__wrap_EmitEvent_i2pd_3cde21bb36a9caa1
func _swig_wrap_EmitEvent(base uintptr)

func EmitEvent(arg1 Std_map_Sl_std_string_Sc_std_string_Sg_) {
	defer SwigCgocallDone()
	SwigCgocall()
	_swig_wrap_EmitEvent(arg1.Swigcptr())
}


type SwigcptrEVP_MD_CTX uintptr
type EVP_MD_CTX interface {
	Swigcptr() uintptr;
}
func (p SwigcptrEVP_MD_CTX) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrDSA uintptr
type DSA interface {
	Swigcptr() uintptr;
}
func (p SwigcptrDSA) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrRSA uintptr
type RSA interface {
	Swigcptr() uintptr;
}
func (p SwigcptrRSA) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrDH uintptr
type DH interface {
	Swigcptr() uintptr;
}
func (p SwigcptrDH) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrBIGNUM uintptr
type BIGNUM interface {
	Swigcptr() uintptr;
}
func (p SwigcptrBIGNUM) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrDSA_SIG uintptr
type DSA_SIG interface {
	Swigcptr() uintptr;
}
func (p SwigcptrDSA_SIG) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrECDSA_SIG uintptr
type ECDSA_SIG interface {
	Swigcptr() uintptr;
}
func (p SwigcptrECDSA_SIG) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_string uintptr
type Std_string interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_string) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrUint64_t uintptr
type Uint64_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrUint64_t) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_map_Sl_std_string_Sc_std_string_Sg_ uintptr
type Std_map_Sl_std_string_Sc_std_string_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_map_Sl_std_string_Sc_std_string_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrNamespace uintptr
type Namespace interface {
	Swigcptr() uintptr;
}
func (p SwigcptrNamespace) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrEVP_PKEY uintptr
type EVP_PKEY interface {
	Swigcptr() uintptr;
}
func (p SwigcptrEVP_PKEY) Swigcptr() uintptr {
	return uintptr(p)
}

